### ISSUE TITLE
Criar função para melhorar o Selective Refresh da seção Featuredpage

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/tema-coletivo#10]
Criar função para melhorar o Selective Refresh da seção Featuredpage

**Comment by everaldomatias** [comment]
O que seria "Selective Refresh"?

**Comment by diegorojas** [comment]
Oi man!

Nois! Mals... deixei muito tacado, era só para registrar para o matheus... mas é uma função parecida com essa aqui que preciso:
https://github.com/brasadesign/tema-coletivo/blob/master/inc/customizer-selective-refresh.php#L215

Ela indica o trecho por seletor que aciona o refresh da pagina para o que vc está editando no customizer, melhorou?
